#!/bin/bash
# Entrypoint script to set up user permissions and start cron

# Don't exit on error for user setup (use || true where needed)
set +e

# Get UID/GID from environment (set via docker-compose)
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# Ensure appuser exists with correct UID/GID
if ! id -u appuser >/dev/null 2>&1; then
    # Create group if it doesn't exist
    if ! getent group ${PGID} >/dev/null 2>&1; then
        groupadd -g ${PGID} appuser 2>/dev/null || true
    fi
    
    # Create user if it doesn't exist
    if ! getent passwd ${PUID} >/dev/null 2>&1; then
        useradd -u ${PUID} -g ${PGID} -m -s /bin/bash appuser 2>/dev/null || true
    fi
fi

# Fix ownership of app directory
chown -R ${PUID}:${PGID} /app 2>/dev/null || true

# Fix ownership of data and logs directories
chown -R ${PUID}:${PGID} /app/data /app/logs 2>/dev/null || true

# Fix ownership of cron log
chown ${PUID}:${PGID} /var/log/cron.log 2>/dev/null || true
chmod 666 /var/log/cron.log 2>/dev/null || true

# Create a script that exports environment variables for cron jobs
# Cron doesn't inherit environment variables, so we need to explicitly set them
# Read environment variables at container start time
PLEX_BASEURL_ENV="${PLEX_BASEURL}"
PLEX_TOKEN_ENV="${PLEX_TOKEN}"
PLEX_LIBRARY_ENV="${PLEX_LIBRARY:-Music}"
DATA_DIR_ENV="${DATA_DIR:-/app/data}"
LOG_FILE_ENV="${LOG_FILE:-/app/logs/cron.log}"
TZ_ENV="${TZ:-UTC}"
PUID_ENV="${PUID:-1000}"
PGID_ENV="${PGID:-1000}"
# Validate delay values - ensure they're positive numbers, use defaults if empty/invalid
DELAY_ALBUM_ENV="${DELAY_AFTER_ALBUM:-0.5}"
DELAY_TRACK_ENV="${DELAY_AFTER_TRACK:-0.2}"
DELAY_ARTIST_ENV="${DELAY_AFTER_ARTIST:-1.0}"
DELAY_API_ENV="${DELAY_AFTER_API_CALL:-0.1}"

# Ensure values are valid (non-empty)
[ -z "$DELAY_ALBUM_ENV" ] && DELAY_ALBUM_ENV="0.5"
[ -z "$DELAY_TRACK_ENV" ] && DELAY_TRACK_ENV="0.2"
[ -z "$DELAY_ARTIST_ENV" ] && DELAY_ARTIST_ENV="1.0"
[ -z "$DELAY_API_ENV" ] && DELAY_API_ENV="0.1"

# Create wrapper script with actual values
cat > /app/cron-env-wrapper.sh << CRONENVEOF
#!/bin/bash
# This script is generated by entrypoint.sh to pass environment variables to cron jobs
# Environment variables are read from the container environment at container start
export PLEX_BASEURL="${PLEX_BASEURL_ENV}"
export PLEX_TOKEN="${PLEX_TOKEN_ENV}"
export PLEX_LIBRARY="${PLEX_LIBRARY_ENV}"
export DATA_DIR="${DATA_DIR_ENV}"
export LOG_FILE="${LOG_FILE_ENV}"
export TZ="${TZ_ENV}"
export PUID="${PUID_ENV}"
export PGID="${PGID_ENV}"
export DELAY_AFTER_ALBUM="${DELAY_ALBUM_ENV}"
export DELAY_AFTER_TRACK="${DELAY_TRACK_ENV}"
export DELAY_AFTER_ARTIST="${DELAY_ARTIST_ENV}"
export DELAY_AFTER_API_CALL="${DELAY_API_ENV}"
exec /app/cron-wrapper.sh "\$@"
CRONENVEOF
chmod +x /app/cron-env-wrapper.sh
chown ${PUID}:${PGID} /app/cron-env-wrapper.sh 2>/dev/null || true

# Install crontab for appuser
# Read cron schedule from environment variable (default: daily at 2 AM)
CRON_SCHEDULE="${CRON_SCHEDULE:-0 2 * * *}"

# Create a temporary crontab with environment variables substituted
# Read environment variables and create crontab with them
PLEX_BASEURL_CRON="${PLEX_BASEURL}"
PLEX_TOKEN_CRON="${PLEX_TOKEN}"
PLEX_LIBRARY_CRON="${PLEX_LIBRARY:-Music}"
DATA_DIR_CRON="${DATA_DIR:-/app/data}"
LOG_FILE_CRON="${LOG_FILE:-/app/logs/cron.log}"
TZ_CRON="${TZ:-UTC}"
PUID_CRON="${PUID:-1000}"
PGID_CRON="${PGID:-1000}"
# Validate delay values - ensure they're positive numbers, use defaults if empty/invalid
DELAY_ALBUM_CRON="${DELAY_AFTER_ALBUM:-0.5}"
DELAY_TRACK_CRON="${DELAY_AFTER_TRACK:-0.2}"
DELAY_ARTIST_CRON="${DELAY_AFTER_ARTIST:-1.0}"
DELAY_API_CRON="${DELAY_AFTER_API_CALL:-0.1}"

# Ensure values are valid (non-empty and numeric)
[ -z "$DELAY_ALBUM_CRON" ] && DELAY_ALBUM_CRON="0.5"
[ -z "$DELAY_TRACK_CRON" ] && DELAY_TRACK_CRON="0.2"
[ -z "$DELAY_ARTIST_CRON" ] && DELAY_ARTIST_CRON="1.0"
[ -z "$DELAY_API_CRON" ] && DELAY_API_CRON="0.1"

# Create a crontab file with environment variables
cat > /tmp/crontab-install << CRONTABEOF
# Cron configuration for Explicit Labeler
# Currently supports Plex only (Emby, Jellyfin, Navidrome planned)
# Environment variables are set by entrypoint.sh
# Schedule is configured via CRON_SCHEDULE environment variable
PLEX_BASEURL=${PLEX_BASEURL_CRON}
PLEX_TOKEN=${PLEX_TOKEN_CRON}
PLEX_LIBRARY=${PLEX_LIBRARY_CRON}
DATA_DIR=${DATA_DIR_CRON}
LOG_FILE=${LOG_FILE_CRON}
TZ=${TZ_CRON}
PUID=${PUID_CRON}
PGID=${PGID_CRON}
DELAY_AFTER_ALBUM=${DELAY_ALBUM_CRON}
DELAY_AFTER_TRACK=${DELAY_TRACK_CRON}
DELAY_AFTER_ARTIST=${DELAY_ARTIST_CRON}
DELAY_AFTER_API_CALL=${DELAY_API_CRON}

# Cron schedule (from CRON_SCHEDULE env var, default: 0 2 * * *)
# Format: minute hour day month weekday command
${CRON_SCHEDULE} /app/cron-env-wrapper.sh >> /var/log/cron.log 2>&1
CRONTABEOF

# Install crontab for appuser
crontab -u appuser /tmp/crontab-install 2>/dev/null || \
su - appuser -c "crontab /tmp/crontab-install" 2>/dev/null || true
rm -f /tmp/crontab-install

# Check if we should run at start
RUN_AT_START=${RUN_AT_START:-true}
if [ "$RUN_AT_START" = "true" ] || [ "$RUN_AT_START" = "1" ]; then
    echo "=========================================="
    echo "Running script at container start..."
    echo "=========================================="
    # Run initial scan directly (environment variables are available in container)
    # We'll run as root first, then switch ownership of any created files
    echo "Running initial scan..." >&2
    cd /app
    # Read environment variables directly (they're set by docker-compose)
    # The variables should be available in the entrypoint's environment
    # Try multiple methods to get them
    PLEX_BASEURL_VAL="${PLEX_BASEURL:-$(printenv PLEX_BASEURL 2>/dev/null || echo '')}"
    PLEX_TOKEN_VAL="${PLEX_TOKEN:-$(printenv PLEX_TOKEN 2>/dev/null || echo '')}"
    PLEX_LIBRARY_VAL="${PLEX_LIBRARY:-$(printenv PLEX_LIBRARY 2>/dev/null || echo 'Music')}"
    
    # Export them for the Python script
    export PLEX_BASEURL="$PLEX_BASEURL_VAL"
    export PLEX_TOKEN="$PLEX_TOKEN_VAL"
    export PLEX_LIBRARY="$PLEX_LIBRARY_VAL"
    
    # Python script will read from environment variables
    if [ -n "$PLEX_BASEURL_VAL" ] && [ -n "$PLEX_TOKEN_VAL" ]; then
        echo "Starting initial scan..." >&2
        python3 mark_explicit_music.py 2>&1 | tee -a /app/logs/cron.log || true
    else
        echo "Warning: PLEX_BASEURL or PLEX_TOKEN not available, skipping initial run" >&2
        echo "  PLEX_BASEURL: ${PLEX_BASEURL_VAL:0:50}..." >&2
        echo "  PLEX_TOKEN: ${PLEX_TOKEN_VAL:0:10}..." >&2
    fi
    # Fix ownership of any files created during initial run
    chown -R ${PUID}:${PGID} /app/data /app/logs 2>/dev/null || true
    echo "Initial run complete. Cron will continue on schedule."
    echo ""
fi

# Start cron as root (cron daemon needs to run as root)
# Cron jobs will execute as appuser (specified in crontab)
exec "$@"

